apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- issuer.yaml
- certificate.yaml

patches:
  - path: manager_patch.yaml
    target:
      kind: Deployment

configurations:
- kustomizeconfig.yaml
